<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>.config</string>
	</array>
	<key>name</key>
	<string>Versatile</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#dialects</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#headers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array</key>
		<dict>
			<key>begin</key>
			<string>\.?([_$[:alnum:]]*)?\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.array.name.versatile</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>array scope, arrayName[.*]</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>meta.array.versatile</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#core-patterns</string>
				</dict>
			</array>
		</dict>
		<key>attribute</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.versatile</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>base scope, attribute of an object</string>
			<key>match</key>
			<string>([_$[:alpha:]][_$[:alnum:]]*)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#index-var</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>booleans</key>
		<dict>
			<key>comment</key>
			<string>true or false</string>
			<key>match</key>
			<string>true|false</string>
			<key>name</key>
			<string>constant.language.versatile</string>
		</dict>
		<key>comments</key>
		<dict>
			<key>begin</key>
			<string>\#</string>
			<key>end</key>
			<string>\#</string>
			<key>name</key>
			<string>comment.line.number-sign.versatile</string>
		</dict>
		<key>core-patterns</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#index-var</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#one-line-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#booleans</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dialect-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>dialect-string</key>
		<dict>
			<key>begin</key>
			<string>\\\"</string>
			<key>comment</key>
			<string>\"Comments inside dialect\"</string>
			<key>end</key>
			<string>\\\"</string>
			<key>name</key>
			<string>string.interpolated.versatile</string>
		</dict>
		<key>dialects</key>
		<dict>
			<key>begin</key>
			<string>(Decoder|Encoder)\.(Versatile|VersatileReport)(\.Dialect).*\s*:(\s*\")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.versatile</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.versatile</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.versatile</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.versatile</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>scope related to dialects (decoder, encoder, ...)</string>
			<key>end</key>
			<string>\"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.versatile</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.dialect.versatile</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#core-patterns</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>function</key>
		<dict>
			<key>begin</key>
			<string>(\??[_$[:alpha:]][_$[:alnum:]]*)\s?\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.function.name.versatile</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>functions scope, functionName(.*)</string>
			<key>contentName</key>
			<string>meta.function.parameters</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#core-patterns</string>
				</dict>
			</array>
		</dict>
		<key>header-string</key>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.versatile</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.versatile</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.versatile</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>macros inside a header string</string>
					<key>match</key>
					<string>(\$\{[^\}]*\})|(\%\%[^\%]*\%\%)</string>
				</dict>
			</array>
		</dict>
		<key>headers</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.versatile</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.versatile</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.headerContent.value.versatile</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#header-string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#booleans</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>comment</key>
			<string>all lines but the dialect lines</string>
			<key>match</key>
			<string>([^\.]*)(\.[^:]*)?[[:alnum:]]*\s*\:\s*(.*)</string>
			<key>name</key>
			<string>meta.headerContent.versatile</string>
		</dict>
		<key>index-var</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.versatile</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>index $i to iterate through an array</string>
			<key>match</key>
			<string>(\$[_$[:alnum:]]*)</string>
			<key>name</key>
			<string>meta.array.index.versatile</string>
		</dict>
		<key>numbers</key>
		<dict>
			<key>match</key>
			<string>\d</string>
			<key>name</key>
			<string>constant.numeric.versatile</string>
		</dict>
		<key>object</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>comment</key>
			<string>object scope</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.object.versatile</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#core-patterns</string>
				</dict>
			</array>
		</dict>
		<key>one-line-attribute</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.versatile</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.versatile</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>hack to color lines of type, attribute = property</string>
			<key>match</key>
			<string>^\s*(\w*)\s*\=\s*(\w*)\s*$</string>
		</dict>
		<key>property</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.versatile</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>.someProperty</string>
			<key>match</key>
			<string>\.([_$[:alnum:]]*)</string>
			<key>name</key>
			<string>meta.property.versatile</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.versatile</string>
	<key>uuid</key>
	<string>5f4ef975-8f06-40c7-a78c-a6e7820644a3</string>
</dict>
</plist>
